auths/urls.py
from django.conf.urls import url
from . import views

# app_name = 'auths'

# urlpatterns = [
#     # /
#     url(r'^', views.index, name='index'),
# ]

mywallet/urls.py
from django.conf.urls import url, include

from . import views
from rest_framework import routers

# router = routers.DefaultRouter()
# router.register(r'wallets', views.WalletList.as_view())

urlpatterns = [
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', views.IndexView.as_view(), name="mywallet"),
    url(r'^logout/', views.LogoutView.as_view(), name="log out"),
    url(r'^addwallet/', views.NewWallet.as_view(), name="add wallet"),
    url(r'^add-new-currency/', views.NewCurrency.as_view(), name='add new currency'),
    url(r'^add-new-operation/', views.NewOperation.as_view(), name='add new operation'),
    url(r'^get-codes-by-wallet-title/', views.GetCodes.as_view(), name="return code by wallet title"),
    url(r'^get-wallets-titles/', views.GetWalletTitles.as_view(), name="get wallets-titles"),
    # url(r'^wallets/', views.GetWallets.as_view(), name="get all wallets"),
    url(r'^edit-wallet-title/', views.EditWalletTitle.as_view(), name="Editing wallet title"),

    url(r'^wallets/', views.WalletList.as_view(), name="wallet-list"),
    # url(r'^api/', include(router.urls)),
    # url(r'^api/api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

wallet/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from auths.views import IndexView, Registration, Authentication

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name="home"),
    url(r'^registration/', Registration.as_view(), name="sign up"),
    url(r'^authentication/', Authentication.as_view(), name="sign in"),
    url(r'mywallet/', include('mywallet.urls')),
]

mywallet/models.py
from django.db import models
from django.conf import settings


class Wallet(models.Model):
    title = models.CharField(max_length=20)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, )

    def __str__(self):
        return self.title


class AccountStatement(models.Model):
    value = models.FloatField()
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.value)


class Currency(models.Model):
    code = models.CharField(max_length=4)
    value = models.ForeignKey(AccountStatement, on_delete=models.CASCADE)

    def __str__(self):
        return self.code


class DiffOperation(models.Model):
    OPERATION_TYPES = (
        ('SP', 'Spending'),
        ('DP', 'Deposit')
    )

    title = models.CharField(max_length=50)
    date = models.DateField()
    sum = models.FloatField()
    operation_type = models.CharField(max_length=2, choices=OPERATION_TYPES)
    wallet_title = models.CharField(max_length=20)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, )
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

mywallet/forms.py
from django import forms
from .models import Wallet
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Button
from crispy_forms.bootstrap import Field, FormActions


class AddOperationForm(forms.Form):
    title = forms.CharField(label='Title', required=True)
    sum = forms.FloatField(label='Sum', required=True)
    wallets = forms.ChoiceField(label='Wallets', required=True)
    code = forms.ChoiceField(label='Codes', required=True)
    date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    helper = FormHelper()
    helper.form_id = 'id-add-operation-form'
    helper.form_method = 'POST'
    helper.form_class = 'form-horizontal, form-group'
    helper.form_show_labels = False
    # helper.form_action = '/add-operation/'

    helper.layout = Layout(
        Field('title', placeholder='Title', css_class='form-control'),
        Field('sum', placeholder='Sum', css_class='form-control'),
        Field('wallets', css_class='form-control'),
        Field('code', css_class='form-control'),
        Field('date', css_class='form-control'),
        FormActions(Button('Add', 'add', css_class='btn, btn-primary'))
    )

mywallet/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponse
from django.contrib.auth import logout
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import TemplateView, View

from .models import Wallet, Currency, AccountStatement, DiffOperation

from datetime import datetime
import json as simplejson

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from rest_framework.decorators import detail_route
from .serializers import WalletSerializer


class IndexView(TemplateView):
    def get(self, request, **kwargs):
        if request.user.is_authenticated():
            operation_list = DiffOperation.objects.filter(user=request.user).order_by('date')
            paginator = Paginator(operation_list, 6)
            page = request.GET.get('page')
            try:
                operations = paginator.page(page)
            except PageNotAnInteger:
                operations = paginator.page(paginator.num_pages)
            except EmptyPage:
                operations = paginator.page(paginator.num_pages)

            return render(request, 'mywallet/mywallet.html', {'operations': operations})
        return HttpResponseRedirect('/')


class LogoutView(TemplateView):
    def get(self, request, **kwargs):
        logout(request)
        return HttpResponseRedirect('/')


class NewWallet(View):
    @staticmethod
    def validate_data(title, code, value, request):
        error_msg = {}
        try:
            float(value)
        except ValueError:
            error_msg['sum'] = 'Currency must be a numeric'

        if len(code) != 3:
            error_msg['type'] = 'Enter correct currency code'

        if title == '':
            error_msg['name'] = 'Title can not be empty'

        if Wallet.objects.filter(user=request.user, title=title):
            error_msg['name'] = 'You are already have this wallet'

        if error_msg:
            error_msg['status'] = '400'
        return error_msg

    @staticmethod
    def add_wallet(user, currency_type, name, value):
        wallet = Wallet(title=name)
        wallet.user = user
        wallet.save()

        statement = AccountStatement(value=value)
        statement.wallet = wallet
        statement.save()

        currency = Currency(code=currency_type)
        currency.value = statement
        currency.save()

    def post(self, request):
        if request.method == 'POST':
            if request.is_ajax():
                name = request.POST.get('name')
                currency_type = request.POST.get('type').upper()
                value = request.POST.get('sum')

                error_msg = self.validate_data(name, currency_type, value, request)

                if not error_msg:
                    self.add_wallet(request.user,
                                    currency_type,
                                    name,
                                    value)

                    error_msg['status'] = '200'
                return HttpResponse(json.dumps(error_msg),
                                    content_type="application/json")

        return HttpResponseRedirect('/')


class NewOperation(View):
    @staticmethod
    def validate_data(operation_type, operation_title, operation_value,
                      date, request, wallet_title):
        error_msg = {}

        try:
            float(operation_value)
        except ValueError:
            error_msg['sum'] = 'Currency must be a numeric'

        if operation_title == '':
            error_msg['name'] = 'Title can not be empty'

        if operation_type != 'SP' and operation_type != 'DP':
            error_msg['type'] = 'Wrong type operation'

        try:
            datetime.strptime(date, "%Y-%m-%d")
        except ValueError:  # find correct exception
            error_msg['date'] = 'Wrong date'

        wallet = Wallet.objects.filter(user=request.user, title=wallet_title)
        if not wallet:
            error_msg['wallet'] = 'Wrong wallet title'

        return error_msg

    @staticmethod
    def add_operation(request, wallet_title, select_value, code, operation_type, operation_value, operation_title,
                      date):
        wallet = Wallet.objects.get(user=request.user, title=wallet_title)
        account = AccountStatement.objects.get(wallet=wallet, value=select_value)
        currency = Currency.objects.get(value=account, code=code)

        new_operation = DiffOperation(title=operation_title, date=date,
                                      sum=operation_value, operation_type=operation_type)
        new_operation.currency = currency
        new_operation.user = request.user
        new_operation.wallet_title = wallet_title
        new_operation.save()
        if operation_type == 'SP':
            account.value -= float(operation_value)
        else:
            account.value += float(operation_value)
        account.save()

    def post(self, request):
        if request.method == 'POST':
            if request.is_ajax():
                operation_type = request.POST.get('type')
                operation_title = request.POST.get('title')
                operation_value = request.POST.get('sum')
                wallet_title = request.POST.get('wallet')
                code = request.POST.get('code')
                date = request.POST.get('date')
                select_value = request.POST.get('select_value')

                error_msg = self.validate_data(operation_type, operation_title, operation_value,
                                               date, request, wallet_title)
                if not error_msg:
                    self.add_operation(request, wallet_title, select_value, code, operation_type, operation_value,
                                       operation_title, date)

                    error_msg['status'] = '200'

                return HttpResponse(json.dumps(error_msg),
                                    content_type="application/json")

            return HttpResponseRedirect('/')


class NewCurrency(View):
    @staticmethod
    def validate_data(title, code, value, request):
        error_msg = {}
        try:
            float(value)
        except ValueError:
            error_msg['sum'] = 'Currency must be a numeric'

        if len(code) != 3:
            error_msg['type'] = 'Enter correct currency code'

        wallet = Wallet.objects.filter(user=request.user, title=title)
        accounts = AccountStatement.objects.filter(wallet=wallet)
        for account in accounts:
            if Currency.objects.filter(value=account, code=code):
                error_msg['type'] = 'You are already have this currency'

        if error_msg:
            error_msg['status'] = '400'

        return error_msg

    @staticmethod
    def add_currency(title, code, value, request):
        wallet = Wallet.objects.get(user=request.user, title=title)

        statement = AccountStatement(value=value)
        statement.wallet = wallet
        statement.save()

        currency = Currency(code=code)
        currency.value = statement
        currency.save()

    def post(self, request):
        if request.method == 'POST':
            if request.is_ajax():
                title = request.POST.get('title')
                code = request.POST.get('code').upper()
                value = request.POST.get('sum')

                error_msg = self.validate_data(title, code, value, request)

                if not error_msg:
                    self.add_currency(title, code, value, request)

                    error_msg['status'] = '200'

                return HttpResponse(json.dumps(error_msg),
                                    content_type="application/json")

        return HttpResponseRedirect('/')


class EditWalletTitle(View):
    def post(self, request):
        if request.method == "POST":
            if request.is_ajax():
                old_title = request.POST.get('oldTitle')
                new_title = request.POST.get('newTitle')
                if new_title != '' and len(new_title) <= 20:
                    error_msg = {'status': '200'}
                    wallet = Wallet.objects.get(user=request.user, title=old_title)
                    wallet.title = new_title
                    wallet.save()
                    return HttpResponse(json.dumps(error_msg),
                                        content_type="application/json")
                else:
                    error_msg = {'title': 'Wrong title'}
                    return HttpResponse(json.dumps(error_msg),
                                        content_type="application/json")
        return HttpResponseRedirect('/')


class GetWalletTitles(View):
    def get(self, request, **kwargs):
        if request.method == 'GET':
            if request.is_ajax():
                wallets = Wallet.objects.filter(user=request.user)
                wallets_data = [{'title': item.title} for item in wallets]
                return HttpResponse(json.dumps(wallets_data), content_type="application/json")
        return HttpResponseRedirect('/')


class GetCodes(View):
    @staticmethod
    def get_values(accounts):
        accounts_dict = {}
        for account in accounts:
            code = Currency.objects.filter(value=account)
            for value in code:
                accounts_dict[str(account)] = str(value)
        return accounts_dict

    def get(self, request, **kwargs):
        if request.method == 'GET':
            if request.is_ajax():
                title = request.GET.get('walletTitle')
                wallet = Wallet.objects.filter(user=request.user, title=title)
                accounts = AccountStatement.objects.filter(wallet=wallet)
                codes = self.get_values(accounts)
                return HttpResponse(json.dumps(codes), content_type="application/json")

mywallet/templates/mywallet/mywallet.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>My Wallet</title>

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}"/>
     <link rel="stylesheet" type="text/css" href="{% static 'mywallet/mywallet.css' %}" />
</head>

<body>
{% load crispy_forms_tags %}

<!--NAVBAR-->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href=/mywallet>Simple Wallet</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav nav-right">
                <li><a>already spent: 1040 / budget: 5000</a></li>
                <li><a id="date-field"></a></li>
                <li><img class="avatar-img img-circle img-responsive center-block" src="/static/mywallet/avatar.png"></li>
            </ul>
        </div>
    </div>
</div>

<!--CONTAINER-->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="#">Main</a></li>
                <li><a href="#">Statistic</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="logout">Log out</a></li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main main-block">
            <h1 class="page-header">Main information</h1>


            <div class="col-md-6">
                <table class="table table-responsive">
                    <tbody>
                    <tr><h3>Operations</h3></tr>
                    {% for operation in operations %}
                    <tr>
                        <td>{{operation.title}}</td>
                        <td>{{operation.wallet_title}}</td>
                        <td>{%if operation.operation_type == 'DP' %}+{%endif%}{%if operation.operation_type == 'SP' %}- {%endif%}{{operation.sum}} ({{operation.currency}})</td>
                        <td>{{operation.date}}</td>
                    </tr>
                    {% endfor %}
                    <!--<tr>-->
                        <!--<td>cinema, party, other</td>-->
                        <!--<td>Visa gold (work card)</td>-->
                        <!--<td>-35.5 (USD)</td>-->
                        <!--<td>12.05.2005</td>-->
                    <!--</tr>-->
                    <!--<tr>-->
                        <!--<td>cinema, party, other</td>-->
                        <!--<td>Visa gold (work card)</td>-->
                        <!--<td>-35.5 (USD)</td>-->
                        <!--<td>12.05.2005</td>-->
                    <!--</tr>-->
                    <!--<tr>-->
                        <!--<td>cinema, party, other</td>-->
                        <!--<td>Visa gold (work card)</td>-->
                        <!--<td>-35.5 (USD)</td>-->
                        <!--<td>12.05.2005</td>-->
                    <!--</tr>-->
                    <!--<tr>-->
                        <!--<td>cinema, party, other</td>-->
                        <!--<td>Visa gold (work card)</td>-->
                        <!--<td>-35.5 (USD)</td>-->
                        <!--<td>12.05.2005</td>-->
                    <!--</tr>-->
                    <!--<tr>-->
                        <!--<td>cinema, party, other</td>-->
                        <!--<td>Visa gold (work card)</td>-->
                        <!--<td>-35.5 (USD)</td>-->
                        <!--<td>12.05.2005</td>-->
                    <!--</tr>-->
                    <!--<tr>-->
                        <!--<td><a>More spending's </a></td>-->
                        <!--<td></td>-->
                        <!--<td></td>-->
                        <!--<td></td>-->
                    <!--</tr>-->
                    </tbody>
                </table>
                 <div>
                     {%if operations%}
                        <span class="step-links">
                            {% if operations.has_previous %}
                                <a href="?page={{ operations.previous_page_number }}">previous</a>
                            {% endif %}

                            <span class="current">
                                Page {{ operations.number }} of {{ operations.paginator.num_pages }}.
                            </span>

                            {% if operations.has_next %}
                                <a href="?page={{ operations.next_page_number }}">next</a>
                            {% endif %}
                         {%endif%}
                        </span>
                    </div>
            </div>


            <div class="col-md-4 add-spending">
                <h3><a id="operation-spending-button" class="btn btn-lg">Spending</a>/<a id="operation-incom-button" class="btn btn-lg">Income</a> </h3>

                <form id="spending-form" class="form-horizontal form-group" role="form">
                    <div id = "spending-title-form" class="form-group">
                        <input type="text" class="form-control" id="spending-title-input" placeholder="Title">
                    </div>
                    <div id = "spending-sum-form" class="form-group input-group">
                        <span id="sum-addon" class="input-group-addon">-</span>
                        <input type="text" class="form-control" id="spending-sum-input" placeholder="Sum">
                    </div>
                    <div id="div_id_wallets" class="form-group">
                        <div class="controls ">
                            <select class="form-control select form-control" id="id_wallets" name="wallets"></select>
                        </div>
                    </div>
                    <div id="div_id_code" class="form-group">
                        <div class="controls ">
                            <select class="form-control select form-control" id="id_code" name="code"></select>
                        </div>
                    </div>
                    <div id="spending-date-form" class="form-group">
                        <input type="date" class="form-control" id="spending-date-input">
                    </div>
                    <a id="spending-button" class="btn btn-primary">Add</a>
                </form>

            </div>





            <div class="col-sm-9 col-md-10">

                <div id="add-button-div" class="col-md-2">
                    <div id="add-wallet-button" class="circle btn center-block"></div>
                </div>
            </div>

        </div>
    </div>
</div>


<script type="text/javascript" src="{% static 'jquery/dist/jquery.min.js' %}"> </script>
<script type="text/javascript" src="{% static 'ajax/dist/ajax.min.js' %}"> </script>
<script type="text/javascript" src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'mywallet/mywallet.js' %}"></script>
<script type="text/javascript" src="{% static 'transparency/dist/transparency.min.js' %}"></script>
</body>
</html>